/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BestallRouteImport } from './routes/bestall'
import { Route as BekraftelseRouteImport } from './routes/bekraftelse'
import { Route as IndexRouteImport } from './routes/index'

const BestallRoute = BestallRouteImport.update({
  id: '/bestall',
  path: '/bestall',
  getParentRoute: () => rootRouteImport,
} as any)
const BekraftelseRoute = BekraftelseRouteImport.update({
  id: '/bekraftelse',
  path: '/bekraftelse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bekraftelse': typeof BekraftelseRoute
  '/bestall': typeof BestallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bekraftelse': typeof BekraftelseRoute
  '/bestall': typeof BestallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bekraftelse': typeof BekraftelseRoute
  '/bestall': typeof BestallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bekraftelse' | '/bestall'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bekraftelse' | '/bestall'
  id: '__root__' | '/' | '/bekraftelse' | '/bestall'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BekraftelseRoute: typeof BekraftelseRoute
  BestallRoute: typeof BestallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bestall': {
      id: '/bestall'
      path: '/bestall'
      fullPath: '/bestall'
      preLoaderRoute: typeof BestallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bekraftelse': {
      id: '/bekraftelse'
      path: '/bekraftelse'
      fullPath: '/bekraftelse'
      preLoaderRoute: typeof BekraftelseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BekraftelseRoute: BekraftelseRoute,
  BestallRoute: BestallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
