/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BestallRouteImport } from './routes/bestall'
import { Route as BekraftelseRouteImport } from './routes/bekraftelse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as KundPreviewReferenceRouteImport } from './routes/kund-preview.$reference'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicApplicationFilesRouteImport } from './routes/api/public/application-files'
import { Route as ApiPublicApplicationRouteImport } from './routes/api/public/application'
import { Route as ApiAdminSendPreviewRouteImport } from './routes/api/admin/send-preview'
import { Route as ApiAdminSeedTestGalleryRouteImport } from './routes/api/admin/seed-test-gallery'
import { Route as ApiAdminApplicationsRouteImport } from './routes/api/admin/applications'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicProjectPreviewReferenceRouteImport } from './routes/api/public/project-preview.$reference'

const BestallRoute = BestallRouteImport.update({
  id: '/bestall',
  path: '/bestall',
  getParentRoute: () => rootRouteImport,
} as any)
const BekraftelseRoute = BekraftelseRouteImport.update({
  id: '/bekraftelse',
  path: '/bekraftelse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KundPreviewReferenceRoute = KundPreviewReferenceRouteImport.update({
  id: '/kund-preview/$reference',
  path: '/kund-preview/$reference',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApplicationFilesRoute =
  ApiPublicApplicationFilesRouteImport.update({
    id: '/api/public/application-files',
    path: '/api/public/application-files',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicApplicationRoute = ApiPublicApplicationRouteImport.update({
  id: '/api/public/application',
  path: '/api/public/application',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSendPreviewRoute = ApiAdminSendPreviewRouteImport.update({
  id: '/api/admin/send-preview',
  path: '/api/admin/send-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSeedTestGalleryRoute = ApiAdminSeedTestGalleryRouteImport.update({
  id: '/api/admin/seed-test-gallery',
  path: '/api/admin/seed-test-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminApplicationsRoute = ApiAdminApplicationsRouteImport.update({
  id: '/api/admin/applications',
  path: '/api/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicProjectPreviewReferenceRoute =
  ApiPublicProjectPreviewReferenceRouteImport.update({
    id: '/api/public/project-preview/$reference',
    path: '/api/public/project-preview/$reference',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bekraftelse': typeof BekraftelseRoute
  '/bestall': typeof BestallRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/kund-preview/$reference': typeof KundPreviewReferenceRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/api/admin/applications': typeof ApiAdminApplicationsRoute
  '/api/admin/seed-test-gallery': typeof ApiAdminSeedTestGalleryRoute
  '/api/admin/send-preview': typeof ApiAdminSendPreviewRoute
  '/api/public/application': typeof ApiPublicApplicationRoute
  '/api/public/application-files': typeof ApiPublicApplicationFilesRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/project-preview/$reference': typeof ApiPublicProjectPreviewReferenceRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bekraftelse': typeof BekraftelseRoute
  '/bestall': typeof BestallRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/kund-preview/$reference': typeof KundPreviewReferenceRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/api/admin/applications': typeof ApiAdminApplicationsRoute
  '/api/admin/seed-test-gallery': typeof ApiAdminSeedTestGalleryRoute
  '/api/admin/send-preview': typeof ApiAdminSendPreviewRoute
  '/api/public/application': typeof ApiPublicApplicationRoute
  '/api/public/application-files': typeof ApiPublicApplicationFilesRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/project-preview/$reference': typeof ApiPublicProjectPreviewReferenceRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bekraftelse': typeof BekraftelseRoute
  '/bestall': typeof BestallRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/kund-preview/$reference': typeof KundPreviewReferenceRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/api/admin/applications': typeof ApiAdminApplicationsRoute
  '/api/admin/seed-test-gallery': typeof ApiAdminSeedTestGalleryRoute
  '/api/admin/send-preview': typeof ApiAdminSendPreviewRoute
  '/api/public/application': typeof ApiPublicApplicationRoute
  '/api/public/application-files': typeof ApiPublicApplicationFilesRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/project-preview/$reference': typeof ApiPublicProjectPreviewReferenceRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bekraftelse'
    | '/bestall'
    | '/email/unsubscribe'
    | '/kund-preview/$reference'
    | '/portfolio/$slug'
    | '/api/admin/applications'
    | '/api/admin/seed-test-gallery'
    | '/api/admin/send-preview'
    | '/api/public/application'
    | '/api/public/application-files'
    | '/api/public/contact'
    | '/api/public/health'
    | '/lovable/email/suppression'
    | '/api/public/project-preview/$reference'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bekraftelse'
    | '/bestall'
    | '/email/unsubscribe'
    | '/kund-preview/$reference'
    | '/portfolio/$slug'
    | '/api/admin/applications'
    | '/api/admin/seed-test-gallery'
    | '/api/admin/send-preview'
    | '/api/public/application'
    | '/api/public/application-files'
    | '/api/public/contact'
    | '/api/public/health'
    | '/lovable/email/suppression'
    | '/api/public/project-preview/$reference'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bekraftelse'
    | '/bestall'
    | '/email/unsubscribe'
    | '/kund-preview/$reference'
    | '/portfolio/$slug'
    | '/api/admin/applications'
    | '/api/admin/seed-test-gallery'
    | '/api/admin/send-preview'
    | '/api/public/application'
    | '/api/public/application-files'
    | '/api/public/contact'
    | '/api/public/health'
    | '/lovable/email/suppression'
    | '/api/public/project-preview/$reference'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BekraftelseRoute: typeof BekraftelseRoute
  BestallRoute: typeof BestallRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  KundPreviewReferenceRoute: typeof KundPreviewReferenceRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ApiAdminApplicationsRoute: typeof ApiAdminApplicationsRoute
  ApiAdminSeedTestGalleryRoute: typeof ApiAdminSeedTestGalleryRoute
  ApiAdminSendPreviewRoute: typeof ApiAdminSendPreviewRoute
  ApiPublicApplicationRoute: typeof ApiPublicApplicationRoute
  ApiPublicApplicationFilesRoute: typeof ApiPublicApplicationFilesRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicProjectPreviewReferenceRoute: typeof ApiPublicProjectPreviewReferenceRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bestall': {
      id: '/bestall'
      path: '/bestall'
      fullPath: '/bestall'
      preLoaderRoute: typeof BestallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bekraftelse': {
      id: '/bekraftelse'
      path: '/bekraftelse'
      fullPath: '/bekraftelse'
      preLoaderRoute: typeof BekraftelseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kund-preview/$reference': {
      id: '/kund-preview/$reference'
      path: '/kund-preview/$reference'
      fullPath: '/kund-preview/$reference'
      preLoaderRoute: typeof KundPreviewReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/application-files': {
      id: '/api/public/application-files'
      path: '/api/public/application-files'
      fullPath: '/api/public/application-files'
      preLoaderRoute: typeof ApiPublicApplicationFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/application': {
      id: '/api/public/application'
      path: '/api/public/application'
      fullPath: '/api/public/application'
      preLoaderRoute: typeof ApiPublicApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/send-preview': {
      id: '/api/admin/send-preview'
      path: '/api/admin/send-preview'
      fullPath: '/api/admin/send-preview'
      preLoaderRoute: typeof ApiAdminSendPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/seed-test-gallery': {
      id: '/api/admin/seed-test-gallery'
      path: '/api/admin/seed-test-gallery'
      fullPath: '/api/admin/seed-test-gallery'
      preLoaderRoute: typeof ApiAdminSeedTestGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/applications': {
      id: '/api/admin/applications'
      path: '/api/admin/applications'
      fullPath: '/api/admin/applications'
      preLoaderRoute: typeof ApiAdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/project-preview/$reference': {
      id: '/api/public/project-preview/$reference'
      path: '/api/public/project-preview/$reference'
      fullPath: '/api/public/project-preview/$reference'
      preLoaderRoute: typeof ApiPublicProjectPreviewReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BekraftelseRoute: BekraftelseRoute,
  BestallRoute: BestallRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  KundPreviewReferenceRoute: KundPreviewReferenceRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ApiAdminApplicationsRoute: ApiAdminApplicationsRoute,
  ApiAdminSeedTestGalleryRoute: ApiAdminSeedTestGalleryRoute,
  ApiAdminSendPreviewRoute: ApiAdminSendPreviewRoute,
  ApiPublicApplicationRoute: ApiPublicApplicationRoute,
  ApiPublicApplicationFilesRoute: ApiPublicApplicationFilesRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicProjectPreviewReferenceRoute: ApiPublicProjectPreviewReferenceRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
